INSERT INTO quotes (quote, characterName, voiceOver)
VALUES ("You remember your phone number? I wrote it down for you, just in case. Put it in your pocket, I don't want you to lose it. OK? You ready?", "Mom", false),
("It's Cady's big day.", "Dad", false),
("I guess it's natural for parents to cry on their kid's first day of school. But, you know, this usually happens when the kid is 5. I'm and until today, I was home-schooled. I know what you're thinking. 'Home-schooled kids are freaks.'", "Cady", true),
("X-Y-L-O-C-A-R-P. Xylocarp.", "kid1", false),
("Or that we're weirdly religious or something.", "Cady", true),
("And on the third day, God created the Remington bolt-action rifle so that Man could fight the dinosaurs. And the homosexuals.", "kid2", false),
(" But my family's totally normal. Except for the fact that both my parents are research zoologists and we've spent the last 12 years in Africa.", "Cady", true),
("I had a great life. But then my mom got offered tenure at Northwestern University. So it was goodbye Africa and hello high school.", "Cady", true),
("Hi. I don't know if anyone told you about me. I'm a new student here. My name is Cady Heron.", "Cady", false),
("Talk to me again and I'll kick your ass.", "Kristen", false),
("You don't wanna sit there. Kristen Hadley's boyfriend is gonna sit there", "Janis", false),
("He farts a lot.", "Janis", false),
("Oh, God, I'm so sorry.", "Cady", false),
("It's not you. I'm bad luck.", "Ms Norbury", false),
("My T-shirt's stuck to my sweater, isn't it?", "Ms Norbury", false),
("So...how was your summer?", "Duvall", false),
("I got divorced.", "Ms Norbury", false),
("My carpal tunnel came back.", "Duvall", false),
("Well, I just wanted to let everyone know that we have a new student joining us. She just moved here all the way from Africa.", "Duvall", false),
("It's pronounced like Katie.", "Cady", false),
("My apologies. I have a nephew named Anfernee, and I know how mad he gets when I call him Anthony. Almost as mad as I get when I think about the fact that my sister named him Anfernee.", "Duvall", false),
("Well, welcome, Cady. And thank you, Mr. Duvall.", "Ms Norbury", false),
("Thanks. Maybe some other time, when my shirt isn't see-through.", "Ms Norbury", false),
("The first day of school was a blur. A stressful, surreal blur. I got in trouble for the most random things.", "Cady", true),
("Oh, I have to go to the bathroom.", "Cady", false),
("Can I have the lavatory pass?", "Cady", false),
("I had never lived in a world where adults didn't trust me, where they were always yelling at me.", "Cady", true),
("Did you see nipple? It only counts if you saw a nipple.", "Jason", false),
("I had a lot of friends in Africa. But so far, none in Evanston.", "Cady", true),
("Is that your natural hair color?", "Damian", false),
("This is Damian. He's almost too gay to function.", "Janis", false),
("Your mom's chest hair! I'm Janis.", "Janis", false),
("Hi, I'm Cady. Do you guys know where Room G 14 is?", "Cady", false),
("Health, Tuesday/Thursday, Room G 14.", "Damian", false),
("I think that's in the back building.", "Janis", false),
("Yeah, that's in the back building.", "Damian", false),
("Watch out, please! New meat coming through! Health...Spanish...You're taking 12th-grade calculus?", "Damian", false),
("Yeah, I like math.", "Cady", false),
("Because it's the same in every country.", "Cady", false),
("That's beautiful. This girl is deep.", "Damian", false),
("Won't we get in some sort of trouble for this?", "Cady", false),
("Why would we get you into trouble? We're your friends.", "Janis", false),
("I know it's wrong to skip class, but Janis said we were friends. And I was in no position to pass up friends. I guess I'll never know what I missed on that first day of health class.", "Cady", true),
("Don't have sex. Because you will get pregnant and die. Don't have sex in the missionary position, don't have sex standing up. Just don't do it, promise? OK, everybody take some rubbers.", "Coach", false),
("Oh, you'll get socialized, all right. A little slice like you.", "Damian", false),
("You're a regulation hottie.", "Janis", false),
("How do you spell your name again, Caddy?", "Janis", false),
("It's Cady. C-A-D-Y.", "Cady", false),
("Yeah, I'm gonna call you Caddy.", "Janis", false),
("In the name of all that is holy, will you look at Karen Smith's gym clothes?", "Damian", false),
("Of course all The Plastics are in the same gym class.", "Janis", false),
("Who are The Plastics?", "Cady", false),
("They're teen royalty. If North Shore was Us Weekly, they would always be on the cover.", "Damian", false),
("That one there, that's Karen Smith. She is one of the dumbest girls you will ever meet. Damian sat next to her in English last year.", "Janis", false),
("She asked me how to spell 'orange'", "Damian", false),
("nd that little one? That's Gretchen Wieners.", "Janis", false),
("he's totally rich because her dad invented Toaster Strudel.", "Damian", false),
("Gretchen Wieners knows everybody's business. She knows everything about everyone.", "Janis", false),
("That's why her hair is so big. It's full of secrets.", "Damian", false),
("And evil takes a human form in Regina George. Don't be fooled, because she may seem like your typical selfish, back-stabbing, slut-faced ho-bag. But in reality, she is so much more than that.", "Janis", false),
("She's the queen bee. The star. Those other two are just her little workers.", "Damian", false),
("Regina George. How do I even begin to explain Regina George?", "Janis", false),
("Regina George is flawless.", "Random", false),
("She has two Fendi purses and a silver Lexus.", "Random", false),
("I hear her hair's insured for $10000.", "Random", false),
("I hear she does car commercials… in Japan.", "Random", false),
("Her favorite movie is Varsity blues.", "Random", false),
("One time, she met John Stamos on a plane.", "Random", false),
("And he told her she was pretty.", "Random", false),
("One time, she punched me in the face. It was awesome.", "Random", false),
("She always looks fierce. She always wins Spring Fling Queen.", "Damian", false),
("I care. Every year, the seniors throw this dance for the underclassmen called The Spring Fling. And whomsoever is elected Spring Fling King and Queen automatically becomes head of the Student Activities Committee.", "Damian", false),
("And since I am an active member of the Student Activities Committee, I would say, yeah, I care.", "Damian", false),
("Damian, you've truly out-gayed yourself. Here. This map is gonna be your guide to North Shore. Now, where you sit in the cafeteria is crucial because you got everybody there.", "Janis", false),
("You got your freshmen, ROTC guys, preps, JV jocks, Asian nerds, cool Asians, varsity jocks, unfriendly black hotties, girls who eat their feelings, girls who don't eat anything, desperate wannabes, burnouts, sexually active band geeks, the greatest people you will ever meet, and the worst.", "Janis", false),
("Beware of The Plastics.", "Janis", false),
("Is your muffin buttered?", "Jason", false),
("Would you like us to assign someone to butter your muffin?", "Jason", false),
("Is he bothering you? Jason, why are you such a skeez?", "Regina", false),
("ou were supposed to call me last night.", "Gretchen", false),
("Jason, you do not come to a party at my house with Gretchen and then scam on some poor, innocent girl right in front of us three days later. She's not interested. Do you wanna have sex with him?", "Regina", false),
("Good. So it's settled. So you can go shave your back now. Bye, Jason.", "Regina", false),
("Bitch.", "Jason", false),
("I'm new. I just moved here from Africa.", "Cady", false),
("I used to be home-schooled.", "Cady", false),
("No, no. I know what home-school is. I'm not retarded. So you've actually never been to a real school before? Shut up. Shut up.", "Regina", false),
("I didn't say anything.", "Cady", false),
("You think you're really pretty", "Regina", false),
("Oh, my God, I love your bracelet. Where did you get it?", "Regina", false),
("Oh, it's so fetch.", "Gretchen", false),
("What is 'fetch'?", "Regina", false),
("Oh, it's, like, slang. From England.", "Gretchen", false),
("o if you're from Africa, why are you white?", "Gretchen", false),
("Oh my God, Karen, you can't just ask people why they're white.", "Regina", false),
(" OK, you should just know that we don't do this a lot, so this is, like, a really huge deal. We wanna invite you to have lunch with us every day for the rest of the week.", "Regina", false),
("On Wednesdays, we wear pink.", "Karen", false),
("Oh, my God! OK, you have to do it, OK? And then you have to tell me all the horrible things that Regina says.", "Janis", false),
("Regina seems sweet.", "Cady", false),
("Regina George is not sweet. She's a scum-sucking road whore! She ruined my life!", "Janis", false),
("She's fabulous, but she's evil.", "Damian", false),
("This isn't about hating her, OK? I just think that it would be, like, a fun little experiment if you were to hang out with them and then tell us everything that they say.", "Janis", false),
("OK, fine. Do you have anything pink?", "Cady", false),
("By eighth period, I was so happy to get to math class. I mean, I'm good at math. I understand math. Nothing in math class could mess me up.", "Cady", true),
("I've only had one other crush in my life. His name was Nfume, and we were 5. It didn't work out. But this one hit me like a big, yellow school bus.", "Cady", true),
("So cute. I mean, A-sub-N equals N plus one over four.", "Cady", false),
("Having lunch with The Plastics was like leaving the actual world and entering 'Girl World'. And Girl World had a lot of rules.", "Cady", true),
("You can't wear a tank top two days in a row, and you can only wear your Hair in a ponytail once a week. So I guess you picked today. Oh, and we only wear jeans or track pants on Fridays.", "Gretchen", false),
("Now, if you break any of these rules, you can't sit with us at lunch. I mean, not just you. Like, any of us. OK, like, if I was wearing jeans today, I would be sitting over there with the art freaks", "Gretchen", false),
("Oh, and we always vote before we ask someone to eat lunch with us because you have to be considerate of the rest of the group. Well, I mean, you wouldn't buy a skirt without asking your friends first if it looks good on you.", "Gretchen", false),
("Right. Oh, and it's the same with guys. Like, you may think you like someone, but you could be wrong.", "Gretchen", false),
("120 calories and 48 calories from fat. What percent is that?", "Regina", false),
("I'm only eating foods with less than 30 percent calories from fat.", "Regina", false),
("It's 40 percent. Well, over equals X over and then you cross-multiply and get the value of X.", "Cady", false),
("So have you seen any guys that you think are cute yet?", "Gretchen", false),
("Well, there's this guy in my calculus class...", "Cady", false),
("No! Oh, no, you can't like Aaron Samuels. That's Regina's ex-boyfriend.", "Gretchen", false),
("OK, irregardless. Ex-boyfriends are just off-limits to friends. I mean, that's just, like, the rules of feminism. Don't worry. I'll never tell Regina what you said. It'll be our little secret.", "Gretchen", false),
("Even though I wasn't allowed to like Aaron, I was still allowed to look at him. And think about him. And talk to him. Hey, Aar...", "Cady", true),
("Hey, you're the Africa girl, right?", "Kevin", false),
("I'm Kevin Gnapoor, captain of the North Shore Mathletes. We participate in math challenges against other high schools in the state, and we can get twice as much funding if we've got a girl. So you should think about joining.", "Kevin", false),
("Regina's like the barbie doll I never had. I'd never seen anybody so glamorous.", "Cady", true),
("You cannot do that. That is social suicide. Damn, you are so lucky you have us to guide you.", "Regina", false),
("Being at Old Orchard Mall kind of reminded me of being home in Africa. By the watering hole. When the animals are in heat.", "Cady", true),
("Oh, this is Susan from Planned Parenthood. I have her test results. If you can have her give me a call as soon as she can. It's urgent. Thank you. She's not going out with anyone.", "Regina", false),
("OK, that was so fetch.", "Gretchen", false),
("Make sure you check out her mom's boob job. They're hard as rocks.", "Gretchen", false),
("Welcome to our home. Just want you to know, if you need anything, don't be shy, OK? There are no rules in this house. I'm not like a regular mom. I'm a cool mom. Right, Regina?", "Mrs George", false),
("OK. I'm gonna make you girls a 'hump day' treat.", "Mrs George", false),
("God, my hips are huge!", "Karen", false),
("At least you guys can wear halters. I've got man shoulders.", "Regina", false),
("I used to think there was just fat and skinny. Apparently, there's a lot of things that can be wrong on your body.", "Cady", false),
("My hairline is so weird.", "Gretchen", false),
("My pores are huge.", "Regina", false),
("My nail beds suck.", "Karen", false),
("I have really bad breath in the morning.", "Cady", false),
("Hey, you guys. Happy hour is from 4 to 6!", "Mrs George", false),
("So, you guys, what is the 411? What has everybody been up to? What is the hot gossip? Tell me everything. What are you guys listening to? What's the cool jams?", "Mrs George", false),
("You girls keep me young. Oh, I love you so much.", "Mrs George", false),
("Come check it out, Cady. It's our Burn Book. See, we cut out girls' pictures from the yearbook, and then we wrote comments.", "Gretchen", false),
("Trang Pak is a grotsky little byotch", "Karen", false),
("Dawn Schweitzer is a fat virgin.", "Gretchen", false),
("Amber D'Alessio. She made out with a hot dog.", "Karen", false),
("He's almost too gay to function.", "Cady", false),
("Oh, no. Maybe that was only OK when Janis said it.", "Cady", true),
("And they have this Burn Book where they write mean things about all the girls in our grade.", "Cady", false),
("Will this minimize my pores?", "Damian", false),
("Caddy, you gotta steal that book.", "Janis", false),
("We could publish it, and then everybody would see what an ax-wound she really is.", "Janis", false),
("Caddy, there are two kinds of evil people. People who do evil stuff, and people who see evil stuff being done and don't try to stop it.", "Janis", false),
("I love seeing teachers outside of school. It's like seeing a dog walk on its hind legs.", "Janis", false),
("My nana takes her wig off when she's drunk.", "Damian", false),
("ou can't join Mathletes. It's social suicide.", "Damian", false),
("retchen told me that you like Aaron Samuels. I mean, I don't care, do whatever you want. But let me just tell you something about Aaron: All he cares about is school and his mom and his friends", "Regina", false),
("I had survived my first three-way calling attack. And with Regina's blessing, I started talking to Aaron more and more. On October 3rd, he asked me what day it was.", "Cady", false),
("Grool. I meant to say 'cool' and then I started to say 'great'.", "Cady", false),
("Hey, Africa. You staying for the Mathletes meeting?", "Kevin", false),
("In Girl World, Halloween is the one night a year when a girl can dress like a total slut and no other girls can say anything about it. The hard-core girls just wear lingerie and some form of animal ears.", "Cady", true),
("Unfortunately, no one told me about the slut rule. ", "Cady", true),
("She tells everybody. It's kind of cute, actually. She's like a little girl. She, like, writes all over her notebook, 'Mrs. Aaron Samuels.' And she made this T-shirt that says 'I heart Aaron' and she wears it under all her clothes.", "Regina", false),
("Well, who can blame her? I mean, you're gorgeous. And OK, look, I'm not saying she's a stalker, but she saved this Kleenex you used and she said she's gonna do some kind of African voodoo with it to make you like her.", "Regina", false),
("This was it. Regina said she would talk to Aaron for me, and now she was.", "Cady", true),
("I know she's kind of socially retarded and weird, but she's my friend, so just promise me you won't make fun of her.", "Regina", false),
("How could Janis hate Regina? She was such a good… Slut!", "Cady", true),
("I had never felt this feeling before. I could hear my heartbeat in my ears. My stomach felt like it was going to fall out my butt. I had this lump in my throat like after you dry-swallow a big pill. I hated Regina. I hated her!", "Cady", true),
("Regina George is an evil dictator. Now, how do you overthrow a dictator? You cut off her resources. Regina would be nothing without her high-status man candy, technically good physique, and ignorant band of loyal followers. Now, Caddy, if we want this to work, you are gonna have to keep hanging out with them like nothing is wrong. Can you do it?", "Janis", false),
("And Regina wanted me to tell you that she was trying to hook you up with Aaron, but he was just interested in getting her back. And that's not Regina's fault.", "Gretchen", false),
("It's called the South Beach Fat Flush, and all you drink is cranberry juice for 72 hours.", "Regina", false),
("Regina was dangling Aaron in front of me on purpose. I knew how this would be settled in the animal world. But this was Girl World.", "Cady", true),
("And in Girl World, all the fighting had to be sneaky.", "Cady", true),
("We kept our eyes open for opportunities for sabotage.", "Cady", true),
("Your face smells like peppermint.", "Aaron", false),
("This is ass, you guys. It's been a month, and all we've done is make Regina's face smell like a foot.", "Janis", false),
("We gotta crack Gretchen Wieners. We crack Gretchen, and then we crack the lock on Regina's whole dirty history.", "Janis", false),
("She's so pathetic. Let me tell you something about Janis Ian. We were best friends in middle school. I know, right? It's so embarrassing. I don't even... Whatever. So then in eighth grade, I started going out with my first boyfriend, Kyle, who was totally gorgeous, but then he moved to Indiana. And Janis was, like, weirdly jealous of him.", "Regina", false),
("Like, if I would blow her off to hang out with Kyle, she'd be like, 'Why didn't you call me back?' And I'd be like, 'Why are you so obsessed with me?' So then, for my birthday party, which was an all-girls pool party, I was like, 'Janis, I can't invite you, because I think you're a lesbian.'", "Regina", false),
("When she came back in the fall for high school, all of her hair was cut off and she was totally weird, and now I guess she's on crack. Oh, my God! I love your skirt. Where did you get it?", "Regina", false),
("That is the ugliest F-ing skirt I've ever seen.", "Regina", false),
("No. I don't send them, I just get them. So you better send me one, byotch. Love you.", "Regina", false),
("I was definitely sending her one. I was gonna use three candy canes to crack Gretchen Wieners.", "Cady", true),
("'Thanks for being such a great friend. Love, Regina.' That's so sweet.", "Cady", false),
("Once Gretchen thought Regina was mad at her, the secrets started pouring out. All I had to do was wait for one we could use.", "Cady", true),
("Welcome to the North Shore High School winter talent show. Let me hear you make some noise. All right, settle down. Our first act calls himself a star on the rise. Let's hear it for Damian.", "Duvall", false),
("Well, I mean, her parents totally don't sleep in the same bed anymore, if that's what you mean. Oh, my God. Don't tell her I told you that.", "Gretchen", false),
("I am beautiful in every single way Yes, words can't bring me down Don't you bring me down today", "Damian", false),
("I mean, no offense, but why would she send you a candy cane? She doesn't even like you that much. Maybe she feels weird around me because I'm the only person that knows about her nose job. Oh, my God. Pretend you didn't hear that.", "Gretchen", false),
("All you sucker Mcs Ain't got nothing on me From my grades to my lines You can't touch Kevin G I'm a Mathlete So nerd is inferred but forget what you heard I'm like James bond the Third Shaken not stirred I'm Kevin Gnapoor The G is silent When I sneak in your door And make love to your woman On the bathroom floor I don't play it like Shaggy You'll know it was me because the next time you see her She'll be like Oh, Kevin G!", "Kevin", false),
("K.G. And the Power of Three. That was something.", "Duvall", false),
("And finally, please welcome to the stage Santa's Helpers doing 'Jingle Bell Rock'.", "Duvall", false),
("Hey, good job, Africa.", "Kevin", false),
("Cady's blushing. Oh, my God. You totally have a crush on that guy.", "Gretchen", false),
("That's why you wanted to join the Mathletes.", "Gretchen", false),
("Look how red she is. You love him. And he totally complimented you. That is so fetch.", "Gretchen", false),
("Gretchen, stop trying to make 'fetch' happen. It's not going to happen.", "Regina", false),
("Gretchen Wieners had cracked.", "Cady", true),
("OK, if you even knew how mean she really is.You know that I'm not allowed to wear hoop earrings, right? Yeah. Two years ago, she told me that hoop earrings were her thing and that I wasn't allowed to wear them anymore. And then for Hanukkah, my parents got me this pair of really expensive white-gold hoops. And I had to pretend like I didn't even like them, and it was so sad. And you know she cheats on Aaron? Yes. Every Thursday he thinks she's doing SAT prep. But really, she's hooking up with Shane Oman in the projection room above the auditorium, and I never told anybody that, because ...I'm such a good friend.", "Gretchen", false),
("Jackpot. Gretchen's secret had put the plan back in motion. After Christmas break, we tried every Thursday to help Aaron catch Regina in the act.", "Cady", true),
("They're these weird Swedish nutrition bars. My mom used to give them to the kids in Africa to help them gain weight.", "Cady", false),
("They're these weird nutrition bars my mom uses to lose weight.", "Cady", false),
("Give me it. It's all in, like, Swedish or something.", "Regina", false),
("Yeah, you know, there's some weird ingredient in them that's not legal in the U.S. Yet.", "Cady", false),
("No. It burns carbs. It just burns up all your carbs.", "Cady", false),
("The weird thing about hanging out with Regina was that I could hate her, and at the same time, I still wanted her to like me.", "Cady", true),
("Same with Gretchen.The meaner Regina was to her, the more Gretchen tried to win Regina back. She knew it was better to be in The Plastics, hating life than to not be in at all. Because being with The Plastics was like being famous. People looked at you all the time, and everybody just knew stuff about you.", "Cady", true),
("That new girl moved here from Africa.", "Random", false),
("I saw Cady Heron wearing Army pants and flip-flops, so I bought Army pants and flip-flops.", "Random", false),
("That Cady girl is hot. She might even be hotter than Regina George.", "Random", false),
("I hear Regina George is dating Aaron Samuels again. The two were seen canoodling at Chris Eisel's Halloween party. They've been inseparable ever since.", "Random", false),
("I was a woman possessed. I spent about 80 percent of my time talking about Regina. And the other 20 percent of the time, I was praying for someone else to bring her up so I could talk about her more.", "Cady", true),
("I don't know. Now that's she's getting fatter, she's got pretty big jugs.", "Janis", false),
("I could hear people getting bored with me. But I couldn't stop. It just kept coming up like word vomit.", "Cady", true),
("I have this theory that if you cut all her hair off, she'd look like a British man.", "Cady", false),
("Yeah, I know. You told me that one before. Hey, I'm having an art show. So why don't you take a night off from your double life. I want you to see it.", "Janis", false),
("You smell like a baby prostitute.", "Janis", false),
("Meanwhile, I was finding any excuse I could to talk to Aaron.", "Cady", true),
("She's cheating on you!", "Cady", false),
("Somebody told him about Shane Oman.", "Regina", false),
("I gave him everything. I was half a virgin when I met him.", "Regina", false),
("You wanna do something fun? You wanna go to Taco Bell?", "Karen", false),
("I can't go to Taco Bell, I'm on an all-carb diet. God, Karen, you are so stupid!", "Regina", false),
("I can put my whole fist in my mouth. Wanna see?", "Karen", false),
("I'm kind of psychic. I have a fifth sense. It's like I have ESPN or something. My breasts can always tell when it's gonna rain. Well, they can tell when it's raining.", "Karen", false),
(" I have to admit, I was mildly horrified when Aaron didn't immediately ask me to be his girlfriend. I mean, I know he was sad, but how much time did he need? Regina had moved on.", "Cady", true),
("Do you guys need anything? Some snacks? A condom? Let me know. Oh, God love you", "Mrs George", false),
("But overall, the plan was going pretty well. Aaron had dumped Regina, and she was unknowingly eating 5000 calories a day. It was time to turn our attention to the army of skanks.", "Cady", true),
(" In January, Regina had put a Spring Fling dress on hold at a store called 1-3-5. But being Plastic, she needed our advice before she could actually buy it.", "Cady", true),
("Cady, all I've been eating are these Kälteen bars. They suck.", "Regina", false),
("No, no, this is just how they work. This is all your water weight. First you bloat, and then you drop 10 pounds like that. Well, the Kälteen bars have burned up all your carbs, and now your body's just running on water. But once the water's gone, then you'll be all muscle. It explains it all on the label.", "Cady", false),
("Yeah, everyone in Africa can read Swedish.", "Cady", false),
("We only carry sizes 1, 3, and 5. You could try Sears.", "Random", false),
("Cady. I need your parents to sign this so they know that you're failing.", "Ms Norbury", false),
("You know what's weird about your quizzes, Cady, is that all the work is right and just the answers are wrong.", "Ms Norbury", false),
("Really. Cady, I know that having a boyfriend may seem like the most important thing in the world right now, but you don't have to dumb yourself down to get guys to like you.", "Ms Norbury", false),
("I know, How would I know right? I'm divorced. I'm broke from getting divorced. The only guy that ever calls my house is Randy from Chase Visa. And you know why? Because I'm a pusher. I push people. I pushed my husband into law school. That was a bust. I pushed myself into working three jobs. And now I'm gonna push you because I know you're smarter than this.", "Ms Norbury", false),
("I hate her! I mean, she's totally failing me on purpose because I didn't join those stupid Mathletes! She was so queer. She was like, 'I'm a pusher, Cady. I'm a pusher.'", "Cady", false),
("Probably. She said she works three jobs. You know, I bet she sells drugs on the side to pay for her pathetic divorce.", "Cady", false),
("ou let it out, honey. Put it in the book.", "Gretchen", false),
("I know it may look like I'd become a bitch, but that's only because I was acting like a bitch.", "Cady", true),
("Oh, my God, I'm not mad at her. I'm worried about her. I think somebody nominated her as a joke or something. And when nobody votes for her, she's gonna have a total meltdown. And who's gonna have to take care of her? Me.", "Regina", false),
("Cady, she's not pretty. I mean, that sounds bad, but whatever. The Spring Fling Queen is always pretty. And the crazy thing is is that it should be Karen, but people forget about her because she's such a slut. Anyway, I gotta go. I'm going to bed.", "Regina", false),
("Is butter a carb?", "Regina", false),
("Regina, you're wearing sweatpants. It's Monday.", "Gretchen", false),
("So that's against the rules and you can't sit with us.", "Gretchen", false),
("These sweatpants are all that fits me right now. Fine. You can walk home, bitches.", "Regina", false),
("Watch where you're going, fat-ass!", "Random", false),
("Gretchen and Karen followed me around all afternoon.", "Cady", true),
("Was I the new queen bee?", "Cady", true),
("We've had these tickets for months. You love Ladysmith Black Mambazo", "Mom", false),
("I think Cady's old enough to spend one night on her own.", "Dad", false),
("I had learned how to control everyone around me.", "Cady", true),
("Hey. I'm having a small get-together at my house tomorrow night. It's just gonna be a few cool people, and you better be one of them, byotch.", "Cady", false),
("Shut up. I love that shirt on you.", "Cady", false),
("Aaron Samuels was going to be in my house at my party. Everything had to be perfect. And this time when Aaron saw me, I wouldn't be caught in some ridiculous costume.", "Cady", true),
("I, like, invented her, you know what I mean?", "Regina", false),
("I wasted too much time being pissed off at Regina. No more liars.", "Aaron", false),
("Although… OK, listen. I mean, I did lie to you once, but you're totally gonna laugh when I tell you, so… I pretended to be bad at math so that you'd help me. But the thing is, I'm not really bad at math. I'm actually really good at math. You're kind of bad at math. Anyways, now I'm failing. Isn't that funny?", "Cady", false),
("Wait. You're failing on purpose? That's stupid.", "Aaron", false),
("Just, you know… I just wanted a reason to talk to you.", "Cady", false),
("Well, because I couldn't. Because of Regina. Because you were her property...", "Cady", false),
("God, you know what? You are just like a clone of Regina.", "Aaron", false),
("Oh, no. It was coming up again. Word vomit. No, wait a minute...actual vomit.", "Cady", true),
("You know I couldn't invite you. I had to pretend to be Plastic.", "Cady", false),
("Hey, buddy, you're not pretending anymore. You're Plastic. Cold, shiny, hard Plastic.", "Janis", false),
("Did you have an awesome time? Did you drink awesome shooters and listen to awesome music, and then just sit around and soak up each other's awesomeness?", "Janis", false),
("You're the one who made me like this so you could use me for your eighth-grade revenge.", "Cady", false),
("God! See, at least me and Regina George know we're mean. You try to act like you're so innocent. Like, 'Oh, I used to live in Africa with all the little birdies and the little monkeys.'", "Janis", false),
("You know what? It's not my fault you're in love with me or something!", "Regina", false),
("See? That is the thing with you Plastics. You think that everybody is in love with you, when actually, everybody hates you. Like Aaron Samuels, for example. He broke up with Regina and guess what. He still doesn't want you. So why are you still messing with Regina, Cady? I'll tell you why. Because you are a mean girl! You're a bitch! Here. You can have this. It won a prize.", "Janis", false),
("And I want my pink shirt back! I want my pink shirt back!", "Damian", false),
("Man, I hate those things. Coach Carr makes us eat those when we wanna move up a weight class.", "Shane", false),
("They make you gain weight like crazy.", "Shane", false),
("This girl is the nastiest skank bitch I've ever met. Do not trust her. She is a fugly slut!", "Regina", false),
("I found it in the girls' bathroom. It's so mean, Mr. Duvall.", "Regina", false),
("Is this true? Trang Pak made out with Coach Carr? Good Lord. What's that say? 'Kaitlyn Caussin is a...'?", "Duvall", false),
("Fat whore.", "Regina", false),
("Why would someone write that? That's just so mean", "Regina", false),
("Don't worry, we're gonna find out who did it.", "Duvall", false),
("There's only three girls in the whole school who aren't in it.", "Regina", false),
("At your age, you're gonna be having a lot of urges. You're gonna want to take off your clothes and touch each other. But if you do touch each other, you will get chlamydia. And die.", "Coach", false),
("Cady Heron, they wanna see you in the principal's office. All right, chlamydia. K-L-A...", "Coach", false),
("Have a seat, Miss Heron. Have you ever seen this before?", "Duvall", false),
("You better get your story straight, Miss Heron, because I'm not messing around here.", "Duvall", false),
("It's not ours, it's Regina's. Yeah, she's trying to make it look like we wrote it, but really, she wrote it", "Gretchen", false),
("Miss Wieners, why would Regina refer to herself as a 'fugly slut'? Miss Smith, this is no time to be laughing. We're gonna get to the bottom of this right now.", "Duvall", false),
("Maybe we're not in that book, because everybody likes us. And I don't wanna be punished for being well-liked. And I don't think my father, the inventor of Toaster Strudel, would be too pleased to hear about this.", "Gretchen", false),
("'Made out with a hot dog'? Oh, my God, that was one time!", "Random", false),
("'Dawn Schweitzer has a huge ass'? Who would write that?", "Random", false),
("'Trang Pak made out with Coach Carr'? And so did Sun Jin Dinh.", "Random", false),
("Whoever wrote it probably didn't think anyone would ever see it?", "Karen", false),
("I hope that nobody else ever does see it.", "Duvall", false),
("Mom, can you pick me up? I'm scared.", "Random", false),
("Too gay to function?!", "Damian", false),
("Hey! That's only OK when I say it.", "Janis", false),
("Ron, come quick! They've gone wild. The girls have gone wild.", "Random", false),
("t was full-tilt jungle madness. And it wasn't going away.", "Cady", true),
("Hey, I pulled these two off each other.", "Coach", false),
("Coach Carr, step away from the underage girls. Let me help you down there. Whoa. Hell, no! I did not leave the Southside for this!", "Duvall", false),
("All junior girls report to the gymnasium immediately! Lmmediately!", "Duvall", false),
("Have you ever walked up to people and realized they were just talking about you? Have you ever had it happen 60 times in a row? I have.", "Cady", true),
("Never in my 14 years as an educator have I seen such behavior. And from young ladies. I got parents calling me on the phone asking, 'Did someone get shot?' I ought to cancel your Spring Fling.", "Duvall", false),
("Now, I'm not gonna do that, because we've already paid the DJ. But don't think that I'm not taking this book seriously. Coach Carr has fled school property. Ms. Norbury has been accused of selling drugs. Now, what the young ladies in this grade need is an attitude makeover. And you're gonna get it right now. I don't care how long it takes, I will keep you here all night.", "Duvall", false),
("I will keep you here until 4. Now, what we're gonna try to do is fix the way you young ladies relate to each other. OK? Lady to lady. So who has a lady problem that they'd like to talk about? Yes?", "Duvall", false),
("Somebody wrote in that book that I'm lying about being a virgin because I use super-jumbo tampons. But I can't help it if I've got a heavy flow and a wide-set vagina.", "Random", false),
("Yeah, I can't do this. Ms. Norbury. You're a successful, intelligent, caring, graceful woman.", "Duvall", false),
("It's not a self-esteem problem. I think they're all pretty pleased with themselves. OK. OK, uh. Everybody close your eyes. I want you to raise your hand if you have ever had a girl say something bad about you behind your back. Open your eyes. Now, close your eyes again. And this time, I want you to raise your hand if you have ever said anything about a friend behind her back. Open them. There's been some girl-on-girl crime here. OK. So, what we could do today is a couple exercises to help you express your anger in a healthy way. ", "Ms Norbury", false),
(" Ms. Norbury had us confront each other directly about the things that were bothering us. And it seemed like every clique had its own problems.", "Cady", true),
("You've been acting really stuck-up ever since you switched to shortfielder. And Dawn agrees with me.", "Random", false),
("Can I just say that we don't have a clique problem at this school? And some of us shouldn't have to take this workshop, because some of us are just victims in this situation.", "Regina", false),
("That's probably true. How many of you have ever felt personally victimized by Regina George? Good. OK, who's next? Who's next? Cady. Do you have anything you wanna own up to?", "Ms Norbury", false),
("You never made up a rumor about anybody?", "Ms Norbury", false),
("Just that you sell drugs.", "Cady", true),
("Nothing that you want to apologize for?", "Ms Norbury", false),
("I couldn't apologize to Ms. Norbury without getting blamed for the whole burn book.", "Cady", true),
(" I'm really disappointed in you, Cady. OK, so we're all here because of this book, right? Well, I don't know who wrote this book, but you all have got to stop calling each other sluts and whores. It just makes it OK for guys to call you sluts and whores. Who here has ever been called a slut? OK, everybody up.", "Ms Norbury", false),
("Ms. Norbury had us write out apologies to people that we'd hurt in our lives.", "Cady", true),
("Alyssa, I'm sorry I called you a gap-toothed bitch. It's not your fault you're so gap-toothed.", "Random", false),
("Gretchen, I'm sorry I laughed at you that time you got diarrhea at Barnes and Noble. And I'm sorry I told everyone about it. And I'm sorry for repeating it now.", "Karen", false),
("Laura, I don't hate you because you're fat. You're fat because I hate you.", "Random", false),
("I just wish we could all get along like we used to in middle school. I wish that I could bake a cake made out of rainbows and smiles, and we'd all eat it and be happy.", "Random", false),
("She doesn't even go here!", "Damian", false),
("Do you even go to this school?", "Ms Norbury", false),
("No. I just have a lot of feelings.", "Random", false),
("I'm sorry that people are so jealous of me. But I can't help it that I'm popular.", "Gretchen", false),
("OK, yeah, I've got an apology. So I have this friend who is a new student this year. And I convinced her that it would be fun to mess up Regina George's life. So I had her pretend to be friends with Regina, and then she would come to my house after and we would just laugh about all the dumb stuff Regina said. And we gave her these candy bar things that would make her gain weight, and we turned her best friends against her. And then... Oh, yeah, Cady… You know my friend Cady. She made out with Regina's boyfriend and then convinced him to break up with her. Oh, God, and we gave you foot cream instead of face wash. God! I am so sorry, Regina. Really, I don't know why I did it. I guess it's probably because I've got a big lesbian crush on you. Suck on that!", "Janis", false),
("Janis! Janis! Janis! Janis!", "Random", false),
("Regina, wait! I didn't mean for that to happen.", "Cady", false),
("To find out that everyone hates me? I don't care.", "Regina", false),
("No! Do you know what everyone says about you? They say that you're a home-schooled jungle freak, who's a less-hot version of me. Yeah. So don't try to act so innocent. You can take that fake apology and shove it right up your hairy...", "Regina", false),
("And that's how Regina George died. No, I'm totally kidding. But she did get hurt. Some girls say they saw her head go all the way around. But that's just a rumor. Some people swear they saw me push her in front of the bus. That was an even worse rumor.", "Cady", true),
("Why are my tribal vases under the sink?", "Mom", false),
("This is the fertility vase of the Ndebele tribe. Does that mean anything to you?", "Mom", false),
("Great. All my friends hate me, and now my mom hates me.", "Cady", false),
("Your mom does not hate you. She's afraid of you. I don't know, maybe we mainstream-schooled you too soon. Maybe you should come back and be home-schooled again for a while.", "Dad", false),
("Remember when we saw those lions fighting over the wart hog carcass? I'll be the wart hog.", "Cady", false),
("You're not a wart hog, you're a lion. Just focus on your studies for a little while. You're still an excellent student, right?", "Dad", false),
("OK. You are… What do they call it? Grounded. You're grounded.", "Dad", false),
("She pushed her in front of the bus.", "Random", false),
("Did your teacher ever try to sell you marijuana or Ecstasy tablets?", "Duvall", false),
("What are marijuana tablets?", "Random", false),
("Mr. Duvall, this is ridiculous. Ms. Norbury does not sell drugs.", "Aaron", false),
("I know, Aaron. But after the allegations against Coach Carr turned out to be extremely true, the school board felt that it was best that we investigate every claim made in this Burn Book.", "Duvall", false),
("That book was written by a bunch of stupid girls who make up rumors because they're bored with their own lame lives.", "Aaron", false),
("Well, unless someone wants to come forward and say, 'I made it all up', this is how we have to handle it. To say that someone...", "Duvall", false),
(" Oh, no. Bye, Aaron. You're gonna hate me forever.", "Cady", true),
("Mr. Duvall. I wrote it.", "Cady", false),
("When you get bit by a snake, you're supposed to suck the poison out. That's what I had to do. Suck all the poison out of my life. I started with Regina, who was living proof that the more people are scared of you, the more flowers you get. Then there was Ms. Norbury, who was living proof that no good deed goes unpunished.", "Cady", true),
("h, hi. Did you wanna buy some drugs?", "Ms Norbury", false),
("Wait. I'll grade it right now. I gotta say, watching the police search my house really was the cherry on top of a fantastic year. How much trouble did you get in for telling the truth?", "Ms Norbury", false),
("You didn't write that whole book yourself. Did you tell Mr. Duvall who else did it?", "Ms Norbury", false),
("No, because I'm trying this new thing where I don't talk about people behind their backs.", "Cady", false),
("That's all right. Getting hit by a bus is pretty good punishment.", "Aaron", false),
("Welcome back, nerd.", "Aaron", false),
("I forgive you. But as my own personal form of punishment, I figured out how you're gonna earn that extra credit.", "Ms Norbury", false),
("Excellent. Great turnout this year.", "Kevin", false),
("OK. Marymount, you sons of bitches. You no-good sons of bitches.", "Kevin", false),
("Don't be. You can do this. There's nothing to break your focus, because not one of those Marymount boys is cute.", "Ms Norbury", false),
("Good evening, ladies and gentlemen. Welcome to the Illinois High School Mathletes State Championship. Let's start the competition. Here is the first question. Twice the larger of two numbers is three more than five times the smaller, and the sum of four times the larger and three times the smaller is 71. What are...? North Shore?", "Random", false),
("That is correct. Question number two. Find an odd three-digit number whose digits add up to 12. The digits are all different, and the difference between the first two digits equals the difference between… - Marymount?", "Random", false),
("Shoot. I was really rusty.", "Cady", true),
("Where's Cady?", "Mom", false),
("She went out.", "Dad", false),
("She's grounded.", "Mom", false),
("Are they not allowed out when they're grounded?", "Dad", false),
("Don't forget to vote for Spring Fling King and Queen, people. These A-holes will represent you for a full calendar year.", "Damian", false),
("I'm gonna vote for Regina George because she got hit by that bus.", "Random", false),
("I'm voting for Cady Heron because she pushed her.", "Random", false),
("She's supposed to be grounded, but he let her out.", "Mom", false),
("We pick the girl too.", "Random", false),
("And from North Shore, Miss Caddy Heron", "Random", false),
("Miss Caroline Krafft seriously needed to pluck her eyebrows. Her outfit looked like it was picked out by a blind Sunday school teacher. And she had some 99-cent lip gloss on her snaggletooth. And that's when I realized, making fun of Caroline Krafft wouldn't stop her from beating me in this contest.", "Cady", true),
("Calling somebody else fat won't make you any skinnier. Calling someone stupid doesn't make you any smarter. And ruining Regina George's life definitely didn't make me any happier. All you can do in life is try to solve the problem in front of you.", "Cady", true),
("The limit is negative one", "Random", false),
("Oh, crap. I lost.", "Cady", true),
("Limits. Why couldn't I remember anything about limits? Limits. That was the week Aaron got his hair cut. Oh, God, he looked so cute. OK, focus, Cady. What was on the board behind Aaron's head? If the limit never approaches anything...", "Cady", true),
("The limit does not exist. The limit does not exist!", "Cady", false),
("Our new state champions, the North Shore Mathletes.", "Random", false),
("Yeah! How do you like me now? You like that? Yeah! Get some! Get some!", "Kevin", false),
("Awesome. You went with the leather sleeves.", "Random", false),
("Africa, you did the damn thing.", "Kevin", false),
("We're gonna look so kick-ass in these when we roll into Spring Fling.", "Kevin", false),
("Cady, this is your night. Don't let the haters stop you from doing your thang.", "Kevin", false),
("Cady, you don't have to punish yourself forever. You're already out.", "Ms Norbury", false),
("All right, do we have all of our nominees for king and queen on the stage? OK, good. I just wanted to say that you're all winners. And I could not be happier that this school year's ending. Here we go. The winner of the Spring Fling King, Shane Oman.", "Duvall", false),
("And your Spring Fling Queen, future co-chair of the Student Activities Board and winner of two gift certificates to the Walker Brothers Pancake House, Cady Heron. Where is Cady? There she is.", "Duvall", false),
("Wow. Thanks. Well, half the people in this room are mad at me. And the other half only like me because they think I pushed somebody in front of a bus. So that's not good.", "Cady", false),
("You know, it's not really required of you to make a speech.", "Duvall", false),
("I'm almost done, I swear. To all the people whose feelings that got hurt by the Burn Book, I'm really sorry. You know, I've never been to one of these things before. And when I think about how many people wanted this and how many people cried over it and stuff...I mean, I think everybody looks like royalty tonight. ", "Cady", false),
("Look at Jessica Lopez. That dress is amazing. And Emma Gerber, I mean, that hairdo must have taken hours, and you look really pretty. So...why is everybody stressing over this thing? I mean, it's just plastic. Could really just… Share it. A piece for Gretchen Wieners, a partial Spring Fling Queen. A piece for Janis Ian.", "Cady", false),
("Seriously, most people just take the crown and go.", "Duvall", false),
("And a piece for Regina George. She fractured her spine, and she still looks like a rock star.", "Cady", false),
("And some for everybody else. God, Mr. Duvall, can you wrap it up?", "Cady", false),
("Thanks. All right, have a good time, everyone.", "Duvall", false),
("Look. I'm a queen.", "Janis", false),
("So are we still in a fight?", "Cady", false),
("Are you still an asshole?", "Janis", false),
("Mmmm, I don't think so.", "Cady", false),
("Well, then I guess we're OK.", "Janis", false),
("I was so nervous. They made us do limits. I thought I was gonna hurl.", "Cady", false),
("In case you're wondering, The Plastics broke up. Regina's spine healed, and her physical therapist taught her to channel all her rage into sports. It was perfect because the jock girls weren't afraid of her. Karen used her special talents to do the morning weather announcements.", "Cady", true),
("Hi. This is Karen Smith. It's 68 degrees, and there's a 30 percent chance that it's already raining.", "Karen", false),
("And Gretchen found herself a new clique and a new queen bee to serve. Aaron went to Northwestern, so I still get to see him on weekends. And me? I had gone from home-schooled jungle freak to shiny Plastic to most hated person in the world to actual human being.", "Cady", true),
("ll the drama from last year just wasn't important anymore. School used to be like a shark tank, but now I could just float.", "Cady", true),
("Finally, Girl World was at peace.", "Cady", true),
("Hey, check it out. Junior Plastics.", "Damian", false),
("And if any freshmen tried to disturb that peace… Well, let's just say we knew how to take care of it. Just kidding.", "Cady", true);


INSERT INTO comments (comment, email)
VALUES ("This site is so FETCH!", "test@testyMcTesterson.com"),
("The limit of this site does not exist!", "adam@yourteacher.com");